#version: '3.8'
#services:
#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.0 # Use your desired version
#    container_name: elasticsearch
#    environment:
#      - discovery.type=single-node
#      - xpack.security.enabled=false # Set to true for security features
#      - ES_JAVA_OPTS=-Xms512m -Xmx512m # Adjust memory allocation as needed
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#    volumes:
#      - elasticsearch-data:/usr/share/elasticsearch/data # Persist data
#volumes:
#  elasticsearch-data:
version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.18.0
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic_net
    environment:
      discovery.type: 'single-node'
      xpack.security.enabled: 'false'
      ELASTIC_PASSWORD: 'password'
      ES_JAVA_OPTS: '-Xmx2g -Xms2g'
    volumes:
      - ./es_data:/var/lib/elasticsearch/data # Persist data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.18.0
    container_name: kibana
    volumes:
      - ./kibana_config:/var/lib/kibana/config/kibana.yml
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTIC_PASSWORD='password'
      - xpack.security.enabled=false
    ports:
      - 5601:5601
    networks:
      - elastic_net

networks:
  elastic_net:
    driver: bridge

volumes:
  es_data:
  kibana_config:
